### ISSUE TITLE
Did you delete this folder

### ISSUE THREAD

**Issue by Lunae1Lumen** [files-community/Files#10750]
### Description

Everytime i lauch the app it will show the message "Did you delete this folder?"  and all other folders will display the same message

### Steps To Reproduce

Open the app and it happens

### Steps to fix

want to access the app without message displaying everytime

### Files Version

2.4.2.0

### Windows Version

Windows 11 home 22H2 22621.963

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/10252708/debug.log)

**Comment by Josh-65** [comment]
Where is it set to open?

**Comment by Lunae1Lumen** [comment]
> Where is it set to open?

i dont know where it is set to open i just download the app from the microsoft store

**Comment by Josh-65** [comment]
You can check in Files settings > Preferences > Start-up settings

**Comment by LongGray** [comment]
> You can check in Files settings > Preferences > Start-up settings

I try different Start-up settings and Its not working. Also the same message appears when i activate show/hide hidden folder option.
The pat is wrong that the file.exe is in the 
![image](https://user-images.githubusercontent.com/67371197/208667333-1925455c-1e00-4b4f-887c-aea8b3828d9d.png)

**Comment by Josh-65** [comment]
2.4.3 might fix the issue but Files should be opening to the Home page not the broken path

**Comment by Lunae1Lumen** [comment]
The 2.4.3 update didnt fix it and have tried changing the start up settings

**Comment by LongGray** [comment]
The same 2.4.3 didn't fix it.
Also "edit" & "remove" is not activated in Preference/Start-up/pages
![image](https://user-images.githubusercontent.com/67371197/208908702-89e4870f-b18d-408b-81dc-c06b545e8f81.png)

**Comment by Josh-65** [comment]
Can you open a separate bug report for the preferences

**Comment by LongGray** [comment]
2.4.4.0 "Did you delete this folder" disappear. So i think the bug is fixed.

**Comment by lfsgame** [comment]
It still happens when executing 'files' from cmd or powershell.

**Comment by Lunae1Lumen** [comment]
the new 2.4.4.0 update did fix the bug
