### ISSUE TITLE
Bug: Cut and paste into the source folder causes source folder to be deleted

### ISSUE THREAD

**Issue by AndreasGalster2** [files-community/Files#11174]
### Description

I just tried to copy some files from desktop... First of all, for some reason it copied all files, even though I only selected 7 or 8 files... Issue number one. I then cut the files and copied them into another folder. But not all files could be copied into the folder because the folder had the same name.

So after cut & paste failure, I tried to do CTRL+Z to undo the cut & paste to get my files back to the desktop. Well, all my files are gone, irreversibly deleted...

### Steps To Reproduce

1. Cut target folder
2. Paste target folder inside itself
4. See error prompt
5. Use ctrl + z to undo
6. Notice that target folder was deleted

### Steps to fix
Skip cutting the source folder

### Files Version

Versi: 2.4.25.0

### Windows Version

OS Version: 10.0.22623.1250

### Log file

[debug.log](https://github.com/files-community/Files/files/10636714/debug.log)

**Is there any way to recover my files?**

**Comment by yaira2** [comment]
Ctrl + Z undoes the paste action, I'm not sure if it's meant to revert the cut action.

**Comment by yaira2** [comment]
Can you try this in File Explorer?

**Comment by AndreasGalster2** [comment]
Not possible to undo in File Explorer. Btw, I just realized that it did restore some files... I got lucky that at least my work files are not deleted but there's at least 90% of all files on the desktop gone. Probably also some folders.

**Comment by yaira2** [comment]
I meant what's the behavior in File Explorer if you cut, paste and then undo?

**Comment by AndreasGalster2** [comment]
If you cut, paste, then undo in File Explorer, it undoes the paste action and returns the files back to where they came from.

**Comment by yaira2** [comment]
Thank you for checking, can you update the description and steps to better reflect the issue?

**Comment by Josh-65** [comment]
If you haven't done any more file editing on the drive with your files recovery might be possible with [Windows file recovery](https://support.microsoft.com/en-us/windows/recover-lost-files-on-windows-10-61f5b28a-f5b8-3cc2-0f8e-a63cb4e1d4c4#:~:text=Frequently%20asked%20questions-,Windows,-File%20Recovery%20%2D%20Summer). There are probably videos on it if you cant figure it out. 
You should also start having automatic backups of important files. OneDrive can be used if there small ones. There others programs that can be used if you look on google.

**Comment by yaira2** [comment]
It seems that this was taken out of context on Reddit, reporting the issue on GitHub was the correct thing to do so that we can work on fixing it.

What I don't appreciate is that it was taken out of context on Reddit. You mentioned you used for Files for over a year and you haven't had this issue until now. I don't want to make light of it, and I certainly apologize for any loss of data but to say it's a very common scenario is misleading. Let's be constructive and work on a fix, perhaps you can add a comment to Reddit inviting developers to help us on this issue whether it's reproducing it or finding a fix.

It seems to me the underlying issue isn't with the undo feature but rather with the error that happened during the file operation. File operations are handled by File Explorer in the background and while some logic is intercepted by Files, most of it is handled by File Explorer.

**Comment by yaira2** [comment]
I see there are a number of errors in the log file but I can't tell outright if any are related to this. Fyi @gave92

**Comment by yaira2** [comment]
@AndreasGalster2 is this a preview version of Windows? This might be a key detail and something we should keep in mind when trying to reproduce the issue.

**Comment by Josh-65** [comment]
Seem there on the beta channel of Windows 11

**Comment by yaira2** [comment]
@Josh-65 can you try to reproduce the error doing paste?

**Comment by AndreasGalster2** [comment]
Yes, the build is a beta build, 22623.1250.

**Comment by Josh-65** [comment]
@AndreasGalster2 Do you have any antivirus that has ransomware protection or are using Windows defender control folder access?

**Comment by yaira2** [comment]
> But not all files could be copied into the folder because the folder had the same name.

Do you mean there were existing files in the folder with the same name? Did the conflicts dialog show?

**Comment by yaira2** [comment]
> I just tried to copy some files from desktop... First of all, for some reason it copied all files, even though I only selected 7 or 8 files...

From the actual desktop or the desktop folder in Files?

**Comment by AndreasGalster2** [comment]
@Yes, I have multiple antivirus software. Avast & paid McAfee.

> > But not all files could be copied into the folder because the folder had the same name.
> 
> Do you mean there were existing files in the folder with the same name? Did the conflicts dialog show?

@yair100 

Here's what I did:

My Desktop had many folders, one of them was the folder that I copied into but a sub-folder within that one. I performed this action from within the files app, being located in the desktop folder.

So the files app selected **all files** on the desktop folder. Not sure why it did that. I just shift selected a few files.

The structure is roughly

Desktop
|-- many subfolders
|-- subfolder1
&nbsp;&nbsp;&nbsp;|-- subfolder
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |-- new folder created in this subfolder & trying to paste into that folder

So from within the Desktop root, it selected all folders, then I cut, and pasted into the new folder.

I, unfortunately, forgot the exact error message that it threw. But my best guess is that it errored because I tried to cut & paste subfolder 1 into "new folder", which obviously can't work. 

Sorry, I might have been a bit harsh. I calmed down a bit, but obviously, I'm not super thrilled about my files being gone 😄

**Comment by yaira2** [comment]
> So the files app selected all files on the desktop folder. Not sure why it did that. I just shift selected a few files.

I think that might be due to this issue #11092, I've set the priority on that issue to urgent.

> So from within the Desktop root, it selected all folders, then I cut, and pasted into the new folder.

Was "new folder" in the clipboard due to the selection bug? I wonder if that's what caused the error"

> Sorry, I might have been a bit harsh. I calmed down a bit, but obviously, I'm not super thrilled about my files being gone 😄

You're right to be upset, this kind of issue should never happen, and I want to thank you for taking the time to help us fix it. A lot of others would have written the post on Reddit without bothering to help us fix it 😂

**Comment by Josh-65** [comment]
>  I have multiple antivirus software. Avast & paid McAfee.

You shouldn't have two antivirus running at once that usually causes issues. It may have also cause this one.

**Comment by AndreasGalster2** [comment]
> 

I suppose the "new folder" would have been in the clipboard, since I essentially cut everything in subfolder 1, trying to past into a deeper folder in that subfolder 1. I updated my above comment with a more readable folder structure for context.

**Comment by Josh-65** [comment]
Can you check the quarantine section of both antivirus they might be in there

**Comment by AndreasGalster2** [comment]
> > But not all files could be copied into the folder because the folder had the same name.
> 
> Do you mean there were existing files in the folder with the same name? Did the conflicts dialog show?

No, there shouldn't have been any conflicting files with the same name. The folder that I copied into was brand new. So it was essentially an empty folder.

**Comment by AndreasGalster2** [comment]
> Can you check the quarantine section of both antivirus they might be in there

Nope, unfortunately not in the quarantine of either antivirus softwares.

> Just to give an update for anyone reading this thread, I managed to reproduce this. If you select a folder and try cut pasting into the source folder, it'll display a prompt that it failed to move the items. This causes the source folder to be deleted.

Is there any way to recover the files? Sadly I didn't have history recovery enabled.

**Comment by Josh-65** [comment]
The only way would be to try Windows file recovery https://github.com/files-community/Files/issues/11174#issuecomment-1418495218

**Comment by yaira2** [comment]
This isn't related to AntiVirus software (would have been easy to recover if that was the case). Unfortunately I don't know of a way to recover the files, there are tools like Disk Digger but I haven't had much success.

**Comment by riverar** [comment]
Recommend trying [Recuva](https://www.ccleaner.com/recuva) (oh no CCleaner bought them) free, see what it finds, then go from there. Would recommend not writing to that drive often or you may overwrite deleted data.

**Comment by yaira2** [comment]
@AndreasGalster2 I took the liberty of updating the steps to reproduce and we'll work on a fix for this asap. Thank you for bringing it to our attention and please share if you find a way to recover the data.

**Comment by hishitetsu** [comment]
I don't thing it is a bug but works as expected.
When I created a folder named 'aaa' and then cut and pasted it into 'aaa' itself, I got an error.
If I undo in this state, folder 'aaa' is deleted because the last successful operation is creating 'aaa'.
If I created a folder named 'aaa' and then created a folder named 'bbb' and then cut and pasted 'aaa' into 'aaa' itself, 'bbb' is deleted when undoing.

In File Explorer, it prompts skip the parent folder or cancel moving.
If selecting skip, other items are successfully moved and can be move back when undoing.
If selecting cancel, items are moved only before canceling and cannot be move back when undoing but the last successful operation is cancelled which is same behavior as Files.

**Comment by yaira2** [comment]
@hishitetsu ctrl + z in File Explorer doesn't delete the folder, we should have the same behavior.

**Comment by hishitetsu** [comment]
In File Explorer, we usually create a folder and rename it. So in this case, the last successful operation is renaming, not creating the folder.
If you create a folder and ctrl + z without renaming, the folder will be deleted.

**Comment by yaira2** [comment]
Can we do the same?

**Comment by hishitetsu** [comment]
1. Disable entering a name when creating a folder like Explorer.
2. Add two histories, creating and renaming.

Or, I think it would be nice to warn when the undo operation is to delete a file.

**Comment by yaira2** [comment]
I like the alternative

**Comment by yaira2** [comment]
That would be great, I'll make it priority to review that PR.

**Comment by hishitetsu** [comment]
Sorry, future request not pull request.
I could submit a pull request, but it would take time.

**Comment by yaira2** [comment]
Ah, my bad, I saw the request part and got excited 😂

**Comment by yaira2** [comment]
I think we can track it here because my understanding is that it'll make sure this doesn't happen again.

**Comment by hishitetsu** [comment]
Ok, I will create very very draft PR soon.
Let's have any further discussion on the PR.

**Comment by yaira2** [comment]
@AndreasGalster2 a fix will be included in the next release. A big shoutout to @hishitetsu for contributing this 🎉

**Comment by yaira2** [comment]
@AndreasGalster2 the fix is available in v2.4.33.

**Comment by yoiang** [comment]
This is still happening for me, especially if I cancel a move operation from the conflicting name dialog. I haven't been able to determine if it's only when cutting from outside of Files or even between two Files locations

**Comment by antontsvil** [comment]
Want to put this here because I think it's related and others might try to investigate this behavior:

**Initiating a cut is not an undo-able operation**. A move or a paste is, but undo-ing after a cut will actually undo your last real undo-able operation like undoing a file create (deleting the file), which it will warn you about. I had the incorrect assumption that ctrl+zing after a cut meant you abandon the cut operation, so I saw all kinds of wild stuff like "It's renaming instead of stopping a cut" or "It's deleting an unrelated file I created instead of stopping a cut" I was this 🤏close to opening a ticket lol

In reality, this behavior works exactly the same in windows explorer (worse because they won't warn you before deleting a file.) 

I think the deletion warning dialogue does a good enough job of navigating this weird case. The alternative (and it's what I see in explorer++) is to greatly limit what's undo-able, so that you can't undo moves, copies, or file/folder creates.

**Comment by beedell-roke** [comment]
> [`#issuecomment-3031773729`](https://github.com/files-community/Files/issues/11174#issuecomment-3031773729)

It's undoable on other OSes, and/or via other DEs' file managers (of which an example is KDE's Dolphin on Fedora 42). I suggest that you file an FR for that, because my expectation would be that a cut is reversible, too.
