### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by gtrevize** [files-community/Files#11282]
### Description

Just installed the App on a fresh Windows 10 laptop, and after less than 24 hours of running, it consumed more than 17 GB of RAM. It maxed out the 32 GB of the laptop and made it almost unusable. I had to terminate it with taskmgr.

### Steps To Reproduce

1. Install the App from MS Store
2. Leave it running for a while
3. Monitor memory consumption

### Steps to fix

Terminate the App using taskmgr

### Files Version

2.4.33.0

### Windows Version

Windows 10 22H2 Build 19045.2486

### Log file

2023-02-12 13:41:39.0278|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-02-12 13:41:40.6831|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\XXXXX\OneDrive
2023-02-12 13:41:40.8878|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-02-12 13:41:41.1717|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-02-12 13:41:45.0146|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive - XXXXXXXXXXXXXXXXXXXXX" mapped to C:\Users\XXXXX\OneDrive - XXXXXXXXXXXXXXXXXXXXX
2023-02-12 13:41:55.1100|INFO|CheckForUpdates|STORE: Checking for updates...
2023-02-12 13:42:07.4894|INFO|OnLaunched|App launched. Launch args type: ProtocolActivatedEventArgs
2023-02-12 13:42:08.6572|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\XXXXX\OneDrive
2023-02-12 13:42:08.8790|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-02-12 13:42:09.0997|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-02-12 13:42:30.6006|INFO|IsRunningOnArm|Running on ARM: False
2023-02-12 13:43:44.0535|WARN|ListRecentFoldersAsync|Access is denied. (0x80070005 (E_ACCESSDENIED))
	System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at Vanara.PInvoke.Shell32.IShellLinkW.Resolve(HWND hwnd, SLR_FLAGS fFlags)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Files.App.Filesystem.RecentItems.<>c__DisplayClass14_1.<ListRecentFoldersAsync>b__2()
2023-02-13 16:42:21.3609|INFO|OnLaunched|App launched. Launch args type: LaunchActivatedEventArgs
2023-02-13 16:42:22.4956|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive" mapped to C:\Users\XXXXX\OneDrive
2023-02-13 16:42:22.7166|INFO|GetDrivesAsync|Drive added: C:\, Fixed
2023-02-13 16:42:22.8502|INFO|GetDrivesAsync|Drive added: D:\, Fixed
2023-02-13 16:42:24.4701|INFO|UpdateDrivesAsync|Adding cloud provider "OneDrive - XXXXXXXXXXXXXXXXXXXXX" mapped to C:\Users\XXXXX\OneDrive - XXXXXXXXXXXXXXXXXXXXX
2023-02-13 16:42:27.6236|INFO|CheckForUpdates|STORE: Checking for updates...

**Comment by Josh-65** [comment]
What tabs and folder did you have open?

**Comment by yaira2** [comment]
I know there are memory leaks but how did you get to 17gb of memory? This would require navigating to hundreds of different folders (really large ones) and opening and closing hundreds of tabs.

We're tracking this in #4180, in the meantime, we recommend closing the app instead of leaving in the background.

**Comment by gtrevize** [comment]
Hi, Yair, and thanks for getting back to me.

I just opened 2 tabs, 1 pane. One was my Downloads folder which has about 50 files and only 5 subfolders; the other one is where I store images for Hyper-V virtual machines, which also has very few files.

One thing that comes to mind, is that I did click on a tar-compressed image and it opened it as a folder decompressing on the fly (similar to zip files on Windows Explorer). However, that tab was closed after only a few minutes.

Please let me know if you need any further information. Currently, I had to stop using the App.

Thanks.

------- Original Message -------

**Comment by yaira2** [comment]
It sounds a little like this issue https://github.com/microsoft/microsoft-ui-xaml/issues/3597, can you upvote/add a comment there mentioning how this is preventing you from using Files?

**Comment by neildmd** [comment]
> It sounds in part like this issue [microsoft/microsoft-ui-xaml#3597](https://github.com/microsoft/microsoft-ui-xaml/issues/3597), can you upvote/add a comment there mentioning how this is preventing you from using Files?

Have the memory leaks been solved in Files yet? 

I'd love to switch permanently but I always have 15+ folders open at a time and that's never going to change due to the nature of my work. 

I see a fix was posted here: https://github.com/bluebird-developers/browser/commit/4a1baf3d82778743d7fd531d90aa79d089a6b53b

**Comment by yaira2** [comment]
It hasn't been fixed yet

**Comment by Pinguin2001** [comment]
> > It sounds in part like this issue [microsoft/microsoft-ui-xaml#3597](https://github.com/microsoft/microsoft-ui-xaml/issues/3597), can you upvote/add a comment there mentioning how this is preventing you from using Files?
> 
> Have the memory leaks been solved in Files yet?
> 
> I'd love to switch permanently but I always have 15+ folders open at a time and that's never going to change due to the nature of my work.
> 
> I see a fix was posted here: [bluebird-developers/browser@4a1baf3](https://github.com/bluebird-developers/browser/commit/4a1baf3d82778743d7fd531d90aa79d089a6b53b)

This isn't a fix for the underlying issue, I'm just manually calling the GC to hopefully release some memory. The underlying issue is sadly still present

**Comment by neildmd** [comment]
> > > It sounds in part like this issue [microsoft/microsoft-ui-xaml#3597](https://github.com/microsoft/microsoft-ui-xaml/issues/3597), can you upvote/add a comment there mentioning how this is preventing you from using Files?
> > 
> > 
> > Have the memory leaks been solved in Files yet?
> > I'd love to switch permanently but I always have 15+ folders open at a time and that's never going to change due to the nature of my work.
> > I see a fix was posted here: [bluebird-developers/browser@4a1baf3](https://github.com/bluebird-developers/browser/commit/4a1baf3d82778743d7fd531d90aa79d089a6b53b)
> 
> This isn't a fix for the underlying issue, I'm just manually calling the GC to hopefully release some memory. The underlying issue is sadly still present

I made some noise in the microsoft-ui-xaml thread, hoping it gets some attention. I won't hold my breath though at this rate...

**Comment by yair100** [comment]
@gtrevize @Pinguin2001 @neildmd we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by Pinguin2001** [comment]
@yair100 After testing it for a while, memory usage seems vastly improved and the issue seems resolved. Thanks a lot for your work!

**Comment by yair100** [comment]
@Pinguin2001 thank you for checking!

**Comment by Pinguin2001** [comment]
> [@Pinguin2001](https://github.com/Pinguin2001) thank you for checking!

No worries! I really have to say, you and your team made substantial improvements to files, it is in a much better state overall and I love you continue to work on it. The startup speed has gone up significantly, ram usage is good and browsing folders is smoother, as well as the context menu. The difference between files prod and preview is like night and day.
