### ISSUE TITLE
Bug: Quick access takes a long time to load

### ISSUE THREAD

**Issue by ThinkSalat** [files-community/Files#11732]
### Description

When I open a new window, quick access takes 3-10 seconds to load. In the native file explorer, it's immediate. There has to be something blocking loading.

Happens on stable and latest releases.

### Steps To Reproduce

Open files, wait for quick access to load

may need to add a network location

### Requirements

When opening files, quick access items should pop up immediately, same behavior as native explorer

### Files Version

version agnostic, works on latest and stable releases

### Windows Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎12/‎5/‎2022 OS build	22621.1413 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Log file

[debug.log](https://github.com/files-community/Files/files/10983023/debug.log)

**Comment by yaira2** [comment]
Can you confirm if you're referring to the sidebar or home page (or both)?

**Comment by ThinkSalat** [comment]
It happens on both - though the disks/interfaces shows up a lot faster. But
neither are as fast as native explorer - the native explorer is pretty
instantaneous on my machine. Files takes about 2 seconds for disks to show
up, then another 6 seconds on top of that for the quick access/favorites
bar.

**Comment by yaira2** [comment]
And to confirm, this is in v2.4.58, right?

**Comment by ThinkSalat** [comment]
Yes it is

**Comment by yaira2** [comment]
@ThinkSalat has anything changed in v2.4.69?

**Comment by lucas-thiebaut** [comment]
@yair100 I am currently in version 2.4.81 and this display problem still continues

**Comment by yaira2** [comment]
@Lukiluc29 how many items are in the list?

**Comment by lucas-thiebaut** [comment]
@yair100 There are 6 items in my quick access

**Comment by yaira2** [comment]
@ThinkSalat thank you for the feedback, can you check to see if there are any improvements in v2.5.20?

**Comment by ThinkSalat** [comment]
unfortunately it's quite a bit worse than before - now when I open Files, it takes anywhere from 5-20 to start. I see the icon and an activity indicator spinning around, then everything loads at once.

**Comment by yaira2** [comment]
> it takes anywhere from 5-20 to start

The splash screen is shown while the app is loading, previously the window wouldn't even show at all during this time. That said, it seems like the issue relating to quick access has been resolved.

**Comment by ThinkSalat** [comment]
Well, I think the underlying issue is not resolved - I can open a
windows explorer window in the blink of an eye, but with Files, it takes
5-20 seconds. I think there's still something not right here

**Comment by yaira2** [comment]
If you compare v2.5.10 side by side with v2.5.20, there is a slight improvement. Quick Access you mentioned is now loading instantly so that resolves this issue.

We'll continue working on improvements to reach our goal of loading Files is less than a second. We already have a couple of improvements but they are currently blocked by issues in the WinAppSdk framework.
