### ISSUE TITLE
Bug: Crash when Moving Renamed File into Folder

### ISSUE THREAD

**Issue by IlyaSulli** [files-community/Files#12688]
### Description

When you are renaming a file name and drag it into a folder before the rename is complete and you drag it into a folder, it causes a crash. (I have tested it with a variety of file types and all crash when this is done

### Steps To Reproduce

1. Right click on a file
2. Select Rename
3. While it has the file name highlighted drag it into a folder

### Requirements

It should cancel the rename and drag it into the folder specified

### Files Version

2.5.2.0

### Windows Version

10.0.23481.1000

### Log File

[debug.log](https://github.com/files-community/Files/files/11833364/debug.log)

**Comment by yaira2** [comment]
Thank you for reporting this issue.

**Comment by yaira2** [comment]
It looks like this was fixed together with #12613. It'll be included in the next update.

**Comment by Lukiluc29** [comment]
> It looks like this was fixed together with #12613. It'll be included in the next update.

Since I had already noticed this bug, I looked into it in developer mode with the latest commits, and I observed that this bug still persists.

**Comment by yaira2** [comment]
@Lukiluc29 can you share a video of the issue?

**Comment by Lukiluc29** [comment]
> @Lukiluc29 can you share a video of the issue?

In Details view, when moving a file, it works fine without any errors. However, the file below "takes" the renaming. If we refresh the view, the renaming applies to another file but without being able to rename them. Also, if we exit and return to the file after renaming, nothing is displayed, and the folder is moved correctly.
![Capture d'écran 2023-06-22 175918](https://github.com/files-community/Files/assets/128183422/27be2657-0648-47aa-88d8-3a188e2d6e52)

When we perform the same procedure in column view, Files consistently crashes. However, if we relaunch it, the file is successfully moved but without the renaming taking place.
