### ISSUE TITLE
App is shifting focus to tabs when fast browsing with arrows in column view

### ISSUE THREAD

**Issue by theyv** [files-community/Files#13813]
### Description

https://github.com/files-community/Files/assets/13101364/9aaa2832-dfcf-4c30-913d-3407a1d26086

Video & title is self explaining. 
I cannot understand what exactly makes it losing focus

### Steps To Reproduce

1. Go to column view
2. Go really fast thru folders
3. App is shifting focus to tabs

### Requirements

App should continue browsing thru folders.

### Files Version

3.0.3.0

### Windows Version

10.0.22621.2500

### Log File

[debug.log](https://github.com/files-community/Files/files/13326254/debug.log)

**Comment by yaira2** [comment]
This was fixed a while ago, but it seems to have been reintroduced.

**Comment by yaira2** [comment]
Is this still an issue in the preview version? https://files.community/download/preview

**Comment by chaosemer** [comment]
Yes, I just tried it out right now and have the same issue. Files version 3.4.5.0.

**Comment by yaira2** [comment]
Thank you!

**Comment by theyv** [comment]
3.5.0.0 and it's still isue

**Comment by theyv** [comment]
any updates after 3 years ?lol

**Comment by Josh65-2201** [comment]
Any one can work on this, no one currently is

**Comment by theyv** [comment]
nvm, i just found https://github.com/LumiBearStudio/SpanFinder

**Comment by yair100** [comment]
> any updates after 3 years ?lol

A number of focus related issues have been resolved, are you still able to reproduce this issue?

**Comment by chaosemer** [comment]
I just tried with Files 4.1.3 and this is still happening regularly.

It's very simple to reproduce, I just switch to column navigation, select a random directory to start in, and then try to navigate quickly with the arrows, entering a few subfolders along the navigation.

**Comment by yair100** [comment]
@chaosemer the fixes haven't been released to stable yet. They will be included in the next release.

**Comment by chaosemer** [comment]
Is there a way I can download a preview build to confirm that this issue is fixed for me? I looked at https://github.com/files-community/Files/actions/runs/28327916481#artifacts (the latest action) and it no longer has any artifacts downloadable.

**Comment by yair100** [comment]
It will be available in the next preview build https://files.community/download. You can also compile the source code to test sooner.
