### ISSUE TITLE
Keep Thumbnails when increasing/decreasing size

### ISSUE THREAD

**Issue by Draise14** [files-community/Files#15057]
### What feature or improvement do you think would benefit Files?

https://github.com/files-community/Files/assets/35357409/5cc28f00-324d-4f12-b18e-4c6cf60cb2a7

Maintain thumbnails while scaling the size of the icons with slider or hotkey action (Mouse scroll for example). 

### Requirements

- Helps user see how large/small they are scaling the thumbnails before they refresh. 
- Allows to CTRL+Mouse Scroll Up/Down to increase/decrease like in other explorer

### Files Version

3.3.0.0

### Windows Version

10.0.22635.3350

**Comment by yaira2** [comment]
Thank you for your feedback, the icons need to be reloaded in order to use the correct resolution. Can you clarify what you had in mind?

**Comment by BiosNod** [comment]
> Thank you for your feedback, the icons need to be reloaded in order to use the correct resolution. Can you clarify what you had in mind?

I think he want a special option "Don't update thumbnails size when grid zoom" (but update in next time when user go to this folder).

By the way why I can't zoom using Ctrl + mouse? It seems this ability was it in previous versions? I can't use it now in 3.3

**Comment by Draise14** [comment]
Let me clarify.

When zooming, the thumbnails disappear. When finish zooming, the thumbnails re-appear. 

Ideally, the thumbnails never disappear, and when it finishes zooming, they re-fresh.

**Comment by BiosNod** [comment]
> Let me clarify.

It's clear. By the way is CTRL+Mouse Scroll Up/Down doesn't work in 3.3 only? Did it work in previous versions?

**Comment by Draise14** [comment]
Glad it's clear. Here is a double cllarifier just in case, this version of an explorer keeps thumbs while scaling.
https://github.com/files-community/Files/assets/35357409/de46d0cc-6480-4e69-9659-2aea3bd3217a

About your question, might be another task - in 3.3.0 works in Grid view only. I added it also to the JSON to get it to also change sizes in the other layouts.

**Comment by yaira2** [comment]
@Draise14 I agree with you and that's how it's already supposed to work. @hishitetsu fyi

**Comment by hishitetsu** [comment]
I didn't even care about the behavior when zoomed in/out. However, if the thumbnails are disappearing every time zoomed in/out, that should be fixed.

**Comment by hishitetsu** [comment]
As far as I have tried, thumbnails are reloaded after zooming in/out without disappearing.

https://github.com/files-community/Files/assets/66369541/7e7662a4-27a7-4266-b0b2-6df320a8ee5d

**Comment by Draise14** [comment]
You can still see the flicker to blank thumbnails on refresh in your video recording, and using mouse scroll with CTRL is it moreso evident. 

**Current:**
Thumbnail size 1
Thumbnail blank (blink on refresh)
Thumbnail size 2

**Suggested:**
Thumbnail size 1
Thumbnail replaced (on refresh)
Thumbnail size 2 
= No blink

**Comment by hishitetsu** [comment]
I think the blanks are not because the thumbnails are reloading, but because the entire page is taking a long time to display.
I mean, it goes like this:

Thumbnail size 1
Thumbnail blank (blink on refresh)
Thumbnail size 1
Thumbnail replaced (after refresh)
Thumbnail size 2

**Comment by AronWick** [comment]
In 3.3, how to enable increase/decrease scrolling with CTRL+mouse?

**Comment by Josh65-2201** [comment]
That is always on for the current layout.

**Comment by yaira2** [comment]
I did some more testing and can confirm that the ‘blinking’ issue is caused by the image control redrawing itself. I’m open to any suggestions you might have, but it seems like this might be a limitation with WinUI.
