### ISSUE TITLE
Bug: Files with glass config - consumes CPU even when in background idle mode

### ISSUE THREAD

**Issue by a4audi4fun** [files-community/Files#18000]
### Description

Files 4.0.24.0 preview consumes CPU even when primary windows is closed but process is idling in background; also not seeing system tray icon even thought I have that enabled in my settings.

### Steps To Reproduce

open then close Files window
monitor CPU usage with standard Windows Resource Monitor

### Files Version

4.0.24.0

### Windows Version

10.0.19045.6691

### User ID

8cdda927-0001-4bec-a7ea-2353ba69aa0a

### Log File

[debug.log](https://github.com/user-attachments/files/24351150/debug.log)

**Comment by Josh65-2201** [comment]
Thanks for the feedback, that isn't related to the glass theme. we're tracking this in the below linked issue. You can check there or click subscribe in the right sidebar for updates.

Also see https://files.community/docs/getting-started/faq#:~:text=How%20to%20Improve%20Performance

**Comment by Josh65-2201** [comment]
System tray issue is tracked in #14610 You can check there or click subscribe in the right sidebar for updates.

**Comment by yair100** [comment]
Do you see the system tray icon if you end the Files process from Task Manager and then restart the app?

**Comment by a4audi4fun** [comment]
@yaira2 - Sorry, have tried that multiple times; system tray icon doesn't show after app restart or system reboot.  Have subscribed to tray icon thread Josh pointed me at.

**Comment by yair100** [comment]
@a4audi4fun we believe the performance issues are resolved in the latest Files Preview build. Can you please try it out and let us know your thoughts? https://files.community/appinstallers/Files.preview.appinstaller

**Comment by a4audi4fun** [comment]
background CPU usage is definitely reduced - ResourceMonitor shows approx 3% on an i7-7700HQ laptop processor though still about double that of Windows Explorer.  FWIW tray icon still doesn't show on my Windows 10 system but as Windows 10 is now officially out ot main stream support though still under the MS extended support option that's not a concern IMO.

**Comment by yair100** [comment]
Thank you for checking.
