### ISSUE TITLE
Support pCloud virtual drive

### ISSUE THREAD

**Issue by xmha97** [files-community/Files#2016]
Hi, I using [pCloud](https://www.pcloud.com/) on my PC.
on Windows Explorer, I can see pCloud virtual drive.
![Windows Explorer](https://user-images.githubusercontent.com/23485114/94838957-2ff6c500-0423-11eb-819c-fe8641f32630.png)
But on [Files UWP](https://github.com/files-community/Files), I can't see pCloud virtual drive.
![Files UWP](https://user-images.githubusercontent.com/23485114/94839340-bb705600-0423-11eb-81e2-96242baf4aeb.png)
However, if I navigate to this address, I can see the pCloud virtual drive.
![Files UWP](https://user-images.githubusercontent.com/23485114/94839496-f2df0280-0423-11eb-9b45-13e5d3045ed1.png)
Please support pCloud virtual drive.
Thanks.

**Comment by gsabater** [comment]
This should be relatively easy to add since navigating to P: already seems to work.
+1

**Comment by iSpeeX** [comment]
Well, not so much. With the last version, I'm getting a blue screen everytime I try to enter "P:\" !
Is it working for you ?

**Comment by xmha97** [comment]
> 
> 
> Well, not so much. With the last version, I'm getting a blue screen everytime I try to enter "P:" !
> Is it working for you ?

Yes, you can see its image above.

**Comment by iSpeeX** [comment]
Did you update the app recently? A new update has just come off.
If it's still working... I'm just unlucky...

**Comment by xmha97** [comment]
Yes, I am using the latest version. (v1.5.0.0)
I can navigate to `P:\`

**Comment by gave92** [comment]
Fixed in latest code.

**Comment by xmha97** [comment]
@gave92 This problem persists and is not resolved, please open this issue.

**Comment by gave92** [comment]
@xmha97 thanks for letting us know. Could you confirm the exact Files version?

**Comment by xmha97** [comment]
# Files version
Files version is: 1.5.0.0
![image](https://user-images.githubusercontent.com/23485114/127226792-c973a15f-72d2-4bd7-a5dd-0a2dc3ed465b.png)
# Windows Explorer
I see pCloud on sidebar:
![image](https://user-images.githubusercontent.com/23485114/127227091-257e4182-4d6f-42de-9919-e24b790aea5c.png)
# Files
I don't see pCloud on sidebar:
![image](https://user-images.githubusercontent.com/23485114/127227256-1bfc30c6-e09f-4a8d-8113-a744e5d7fc3e.png)
But can be accessed by typing its path:
![image](https://user-images.githubusercontent.com/23485114/127227626-2666f3c8-4d7f-4e4f-9b57-e63f0f13072b.png)

**Comment by gave92** [comment]
Thanks for confirming @xmha97. The issue is fixed only in the current beta version of Files, 1.5.0.0 does not include the fix.

**Comment by xmha97** [comment]
How I can download the beta version of the Files app?

**Comment by gave92** [comment]
To get the beta version of Files:

Join the insider flight group
You can fill out this form to get access to the preview builds in the Microsoft Store https://forms.office.com/r/UsaBmzC99n. It can take a couple of days until you're added to the flight group, but once added, you will start receiving updates to the regular Files app through the Microsoft Store.
