### ISSUE TITLE
Accesibility: Few buttons/elements and breadcrumb missing descriptive UIA names

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#2134]
**Describe the bug**
A clear and concise description of what the bug is and why it is more urgent than other issue reports. Can't answer this? Please return to the previous page and file a regular bug/feature report.

A few buttons in Files - Preview are missing UIA names resulting in them being announced as "button" instead of a descriptive name indicating what the function of the button is.

In addition to the missing UIA names for the buttons, the *breadcrumb* and it's item do not have UIA names resulting in them being announced as their type (Files.Views.Pager.PathBoxItem) and not by the path they are representing (e.g. "Downloads").

Accessibility Insights view:
![Image showing faulty button description](https://user-images.githubusercontent.com/16122379/96937698-0c2a1a80-14c9-11eb-8a2d-04b79b2c47d5.png)

**To Reproduce**
1. Open a folder in Files
2. Start narrator and navigate through page, observe how certain elements are being announced.

**Expected behavior**

All controls should have (somewhat) descriptive UIA names, not just their type or nothing at all.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Preview Build 202036
 - App version: v0.17.0.0

**Additional context**

**Log file**
I doubt that you need them in this case, but here they are:
[debug.txt](https://github.com/files-community/Files/files/5426326/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5426327/debug_fulltrust.txt)

**Comment by yaichenbaum** [comment]
#2139 should resolve this issue.

**Comment by chingucoding** [comment]
#2139 did not fix the issue with the breadcrumbs being announced as "Files.Views.Pager.PathBoxItem" instead of a descriptive UIA name. Should I open a new issue or do you want to reopen this issue?

**Comment by yaichenbaum** [comment]
@chingucoding I didn't realize this issue included those, can you reopen and edit the description?

**Comment by chingucoding** [comment]
Updated the title and adjusted the description (even though it already included the breadcrumb). Unfortunately, I can't reopen this issue, so this is something you have to do.

**Comment by yaichenbaum** [comment]
@chingucoding Thank you for editing the description, I will try to work on this later today.

**Comment by yaichenbaum** [comment]
@chingucoding Also, my appoligies for missing that you included the breadcrumb the first time, I was going off the screenshot you shared and somehow missed it.

**Comment by chingucoding** [comment]
Don't worry about it, the order of text and screenshot was chosen poorly on my side.
