### ISSUE TITLE
Touch sometimes doesn't open items

### ISSUE THREAD

**Issue by Concorde1234** [files-community/Files#2279]
**Describe the bug**
Folders sometimes would not open when I use touch and pen inputs which make it difficult to open folders when not using a keyboard and mouse 

**To Reproduce**
1. Open Files app 
2. Click on OneDrive then go to a folder
3. Click on the folder
4. Doesn't open and sometimes shows an error message

**Expected behavior**
For it to open as expected.

**Desktop (please complete the following information):**
 Edition	Windows 10 Home
Version	20H2
Installed on	‎6/‎16/‎2020
OS build	19042.610
Experience	Windows Feature Experience Pack 120.2212.31.0

App Version: 0.19.0.0

**Log file**
[debug.txt](https://github.com/files-community/Files/files/5508126/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5508127/debug_fulltrust.txt)

**Comment by frbona** [comment]
Just to get some updates related to this issue.
Is there any plan to get it solved in next release ?

**Comment by yaichenbaum** [comment]
@frbona Do you have this issue in all the layout modes?

**Comment by Concorde1234** [comment]
I'm not sure, I have not used touch in layout mode.


Sent from my Galaxy



-------- Original message --------
From: Yair Aichenbaum ***@***.***>
Date: 3/13/21 4:54 PM (GMT-08:00)
To: files-community/Files ***@***.***>
Cc: Concorde1234 ***@***.***>, Author ***@***.***>
Subject: Re: [files-community/Files] Touch sometimes doesn't open items (#2279)


@frbona<https://github.com/frbona> Do you have this issue in all the layout modes?

**Comment by frbona** [comment]
No, it seems this occur only in list view mode

**Comment by yaichenbaum** [comment]
@frbona That makes sense, the details layout is using an older DataGrid control that isn't very optimized for touch. The WinUI library is going to be working on a new control and we will switch to it when it's ready.

**Comment by frbona** [comment]
Is the new DataGrid included in last release ?

**Comment by yaichenbaum** [comment]
@frbona The WinUI DataGrid hasn't been created yet, I am linking the discussion here so you can upvote/comment on the issue and hopefully increase the priority for Microsoft. https://github.com/microsoft/microsoft-ui-xaml/issues/1500

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by frbona** [comment]
Hi,

After several tests, issue still occur on some big size folders

Thx,
François-Regis

Envoyé de mon Galaxy S21+ 5G Orange
Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by yaichenbaum** [comment]
@frbona Are you sure you tested the new details layout in `main`?

**Comment by frbona** [comment]
I am just testing list view. Which view are ypu calling 'main' ?

Envoyé de mon Galaxy S21+ 5G Orange
Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________
