### ISSUE TITLE
Bug rename file/folder on Details View

### ISSUE THREAD

**Issue by ariadevl** [files-community/Files#2963]
**Describe the bug**
There is bug on renaming file on details view with mouse/touchpad. No problem with other views

**To Reproduce**
1. Change view to Details View
2. Rename file/folder
3. **Click/select/move the cursor to the text position with MOUSE/TOUCHPAD**
4. And then back to selection

**Expected behavior**
When click/select/move cursor to text position, the cursor position changed

**Screenshots**
![QSnr3S9C4D](https://user-images.githubusercontent.com/61529802/104408624-5fc77400-559f-11eb-8c02-ad1c08007b59.gif)

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2 19042.685]
 - App version: [v1.0.0.0]

**Comment by winston-de** [comment]
This should be resolved with the new details view.

https://user-images.githubusercontent.com/59544401/116586451-56ec7b00-a8ce-11eb-9ad1-7eae7424f1b7.mp4

**Comment by yaichenbaum** [comment]
@winston-de This is still an issue if you click in a blank area and then click on the file again.

**Comment by winston-de** [comment]
@yair100 I'm having trouble reproducing this. Is it possible you could make a screen recording?

**Comment by esibruti** [comment]
@yair100 I think we can close this

**Comment by yaichenbaum** [comment]
@esibruti this is still an issue in `main`.

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.
