### ISSUE TITLE
Tab header icon:  Improve drive type check method

### ISSUE THREAD

**Issue by XPoppyX** [files-community/Files#3195]
Currently to show the drive icon in the tab header, the type is checked only by the letter.

**Drive letter: A or B** = Floppy disk icon

**Any other letter** = Hard disk icon

**Comment by gave92** [comment]
Also #3054

**Comment by yaichenbaum** [comment]
This issue should be resolved with #3211.

**Comment by XPoppyX** [comment]
It is not fixed
![Captura de pantalla 2021-01-25 135735](https://user-images.githubusercontent.com/61259627/105737987-516d4680-5f15-11eb-9c86-f13a0b1f20ed.png)

**Comment by yaichenbaum** [comment]
@suvrat29

**Comment by suvrat29** [comment]
> @suvrat29 

I'll look into it

**Comment by suvrat29** [comment]
> It is not fixed
> ![Captura de pantalla 2021-01-25 135735](https://user-images.githubusercontent.com/61259627/105737987-516d4680-5f15-11eb-9c86-f13a0b1f20ed.png)
> 
> And for **network drives** it keeps showing the hard drive icon:
> ![Captura de pantalla 2021-01-25 140043](https://user-images.githubusercontent.com/61259627/105738381-bb85eb80-5f15-11eb-8650-1c5c10255fe5.png)
> 
> **MainPage.xaml**
> 
> ![Captura de pantalla 2021-01-25 141204](https://user-images.githubusercontent.com/61259627/105740102-9befc280-5f17-11eb-8741-db388f3cf9ac.png)

May I know what is the drive type for you B: drive?

**Comment by suvrat29** [comment]
@XPoppyX Also, what is the type of network drive for drive D: ? For me it shows the drive correctly if the drive is A: (and a network drive)

![image](https://user-images.githubusercontent.com/37221647/105742935-1c3b1580-5f62-11eb-990f-823730eff599.png)

**Comment by suvrat29** [comment]
Oh wait! I think I got it, apologies. Fix will be coming shortly. I didn't handle the changes for Tab icons. I did only for the drive widgets.

**Comment by suvrat29** [comment]
@yaichenbaum I have added a new commit [https://github.com/files-community/Files/pull/3285/commits/cfc7970da5549a558653be7f208171e5920e92de](url) which will fix this issue. 
**Note**: To fix both issues: #3195 (this) and #3211, the above mentioned commit and the commit [https://github.com/files-community/Files/commit/502a4117330717e36df05388f8ed4709be47f541](url) will be required.

**Comment by suvrat29** [comment]
@XPoppyX, @yaichenbaum 
The drives have their own icons according to types :-
For  network drives
![DI1](https://user-images.githubusercontent.com/37221647/105756843-2b768f00-5f73-11eb-8491-ade5a62729ae.png)

For regular (fixed) drives and external hard drives
![DI2](https://user-images.githubusercontent.com/37221647/105756866-34fff700-5f73-11eb-9dc8-f89452e86b79.png)

For USB drives
![DI3](https://user-images.githubusercontent.com/37221647/105756959-5234c580-5f73-11eb-940a-0429d3e05fea.png)

For CD/DVD drives
![DI5](https://user-images.githubusercontent.com/37221647/105756969-582aa680-5f73-11eb-8894-4d39fc32306d.png)

**Comment by XPoppyX** [comment]
nice
