### ISSUE TITLE
新版Windows打开回收站闪退

### ISSUE THREAD

**Issue by Majockred** [files-community/Files#3528]
**Desktop (please complete the following information):**
 - OS Version: [ Windows 10 2004 21301.1010]

**Turn On " Experimental--Cache file and folders for better performance ", This error will occur

**Log file**

[debug.txt](https://github.com/files-community/Files/files/5962639/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/Files/files/5962640/debug_fulltrust.txt)

ug_fulltrust.txt.

**Comment by gave92** [comment]
@winston-de do you think this has been fixed with #3514?

**Comment by winston-de** [comment]
@gave92 #3514 Didn't fix any crashes that I know of. It fixed the issue where shortcuts would just be de-serialized as normal ListedItems and not as ShortcutItems.

**Comment by gave92** [comment]
@winston-de From the stacktrace I believe this could happen before your PR when navigating to recycle bin and ordering the elements by deletion date.
