### ISSUE TITLE
change drag and drop start behavior to match the explorer

### ISSUE THREAD

**Issue by nt4f04uNd** [files-community/Files#4257]
**Is your feature request related to a problem?**
fidelity. i used to how this works in explorer

**Describe the solution**
1. in tile mode drag and drop should:
  * start immediately when started from the text
  * be ignored if text wasn't hit (and if item is not in selection already) and allow to have a selection area instead
2. in grid mode it should immedately start as soon as file is hit

currentily it:
1. in tile mode always starts drag and drop, so you can't create a selection from the empty space between the text in tile
2. in grid mode you have to select the item before you can d&d - which makes you tap on it twice

**Describe alternatives you've considered**
none

https://user-images.githubusercontent.com/39104740/112210053-4429bb00-8c2b-11eb-864e-bb34ba31b560.mp4

https://user-images.githubusercontent.com/39104740/112210028-396f2600-8c2b-11eb-8251-bb8cc229360c.mp4

https://user-images.githubusercontent.com/39104740/112210518-d7fb8700-8c2b-11eb-8a66-a242bad83ef1.mp4

https://user-images.githubusercontent.com/39104740/112210556-e47fdf80-8c2b-11eb-8927-b91b7c17f566.mp4

**Comment by XPoppyX** [comment]
> 1. in grid mode it should immedately start as soon as file is hit

_Allow dragging files and folders without selecting them first_ #673

**Comment by mangoepic** [comment]
My mind is just blown right now, that you can draw a selection when not clicking on the text or selected item in Windows Explorer. Didn't know this.

Did this get fixed with #4626?

Or is this request here more about the selecting text functionality?

**Comment by nt4f04uNd** [comment]
Yes, the part of this issue about double click was resovled I guess. The part about selection from the empty area is still valid I believe

**Comment by oooooooooooooooo** [comment]
Still having this issue on the newest public build. Thank you for the video report!
