### ISSUE TITLE
7zip fails when dragging a file/folder into a folder opened in Files

### ISSUE THREAD

**Issue by olnor18** [files-community/Files#4363]
**Explain the bug**
When using 7zip it seems that Files does not handle the drag and drop file moving correctly. This works in Windows Explorer but fails in Files

**To reproduce**
1. Go to a zip archive opened in 7zip
2. Drag a folder or file from 7zip into the Files window
3. See the error in 7-Zip: "The object invoked has disconnected from its clients."

**Expected behavior**
The file should be copied into the folder without error. 

**System Information**
 - OS Version: Windows 10 Pro Insider Preview 21337.1010
 - App version: 1.5.2.0

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5273.

**Comment by tellmewhy12** [comment]
@yair100 I still have this issue 🙋‍♂️

https://user-images.githubusercontent.com/71931749/133414306-74d04f33-7f8a-4cd0-bd5a-a6729f79bc60.mp4

Version: 2.0.12.0
OS Version: 10.0.19043.1165

**Comment by yaichenbaum** [comment]
@mangoepic can you open a new issue and upload the logs so that it doesn't get lost?
