### ISSUE TITLE
Improving the logic for auto changing the layout mode

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#4540]
**Is your feature request related to a problem?**
The layout mode will change from detail view to tiles randomly in folder. There is not pattern i can see it will randomly change it when I open a folder.

**Describe the solution**
Fix the issue where it's randomly changing the layout mode.

**Additional comment**
Logs in case they can be used to fix how layouts will change automatically.
[debug_fulltrust.txt](https://github.com/files-community/Files/files/6290224/debug_fulltrust.txt)
[debug.txt](https://github.com/files-community/Files/files/6290223/debug.txt)

**Comment by yaichenbaum** [comment]
We are working on improving this feature, can you provide details of what kinds of items were in the folders that unexpectedly change layout modes?
Fyi @d2dyno1

**Comment by josh-65** [comment]
It quite random most of the time mostly exe, dll and folders only directorys.

**Comment by d2dyno1** [comment]
@yair100 we could add an option to disable Adaptive Layout

**Comment by yaichenbaum** [comment]
@d2dyno1 Before doing that, we should tweak the behavior, I had this issue as well, but I think that once it's fixed, we won't need a setting.

**Comment by yaichenbaum** [comment]
@d2dyno1 Can you adjust the adaptive layout feature to work correctly with the file types Josh mentioned? I can reproduce this issue as well.

**Comment by d2dyno1** [comment]
@josh-65 Could you share a screen recording of that issue

**Comment by josh-65** [comment]
I can try get a video of it happening. but i have found that there no pattern based on the amount or what's in the folders.

**Comment by josh-65** [comment]
This turned to grid view when I went into it.
![image](https://user-images.githubusercontent.com/26977075/115959724-86356d80-a505-11eb-80a1-25fcd18aa26c.png)

**Comment by d2dyno1** [comment]
> Documents folder turned to grid view with these files in it.
> ![image](https://user-images.githubusercontent.com/26977075/115959724-86356d80-a505-11eb-80a1-25fcd18aa26c.png)

Ahh.. I see 👀 There's a logic that adaptive layout follows so there's no random guessing. You can take a look at this logic here: https://github.com/files-community/Files/blob/main/Files/Helpers/AdaptiveLayoutHelpers.cs#L11

**Comment by josh-65** [comment]
Currently I found the .ini, .bin and .dll files will make it go to grid mode which it shouldn't.

**Comment by yaichenbaum** [comment]
> still would be nice to disable it entirely

That's fair feedback, before looking into that though, we plan to improve the actual feature. In the meantime, you can turn it off by turning off the option to use individual settings for different locations.

**Comment by josh-65** [comment]
just to let you know I have updated listed the extension that change it to grid mode.

**Comment by yaichenbaum** [comment]
@d2dyno1 Can I assign you this issue?

**Comment by d2dyno1** [comment]
Sure, I've been bit busy recently but this shouldn't be much work.

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5140.

**Comment by josh-65** [comment]
On 1.5.32 it still an issue for .mrimg (Marcum reflect backup files) and sometimes folder only directory.

Updated logs:
[debug_fulltrust.log](https://github.com/files-community/Files/files/6644587/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/6644589/debug.log)

**Comment by yaichenbaum** [comment]
@josh-65 How many items are in the directory?

**Comment by josh-65** [comment]
usually about 3 to 5. happened with a .vhdx (Hyper-V hard disk) too

**Comment by yaichenbaum** [comment]
This is currently the expected behavior for directories with less than 6 items, but @d2dyno1 is working on changing it.
