### ISSUE TITLE
Right-click on image files will cause Files to hang up

### ISSUE THREAD

**Issue by shanoaice** [files-community/Files#4828]
**Explain the bug**
Right-click on image file (suffix tested: `.jpg`, `.png`) will cause Files to hang up and silently exits after a while.

**To reproduce**
1. Go to any folder.
2. Right-click on a random image file.
3. Files hang up.

**Expected behavior**
A right-click menu appears.

**Logfile**
[Pastebin - debug.txt](https://pastebin.com/DD8xC9Kb)
[Pastebin - debug_fulltrust.txt](https://pastebin.com/ag8vafhc)

**System Information**
 - OS Version: Windows 10 Home 21H1 Dev Build 21364.1011
 - App version: v1.5.0.0

**Additional comment**
Add any other comment about the problem here. Does this problem happen again after restarting the app? yes
Also, on the most recent Windows Dev Preview, Files won't even start correctly.

**Comment by winston-de** [comment]
Thanks for reporting this. This issue should be resolved with #4625.

**Comment by shanoaice** [comment]
> Thanks for reporting this. This issue should be resolved with #4625.

@winston-de Actually, when I tried to build the app from the latest source, this pull request only partially solved the problem. Now when I right click on any file (not just image file), the app will hang up for about 5 seconds, and then pop a context menu. Is that the right thing to happen?
