### ISSUE TITLE
Can't remove file extensions with rename option

### ISSUE THREAD

**Issue by josh-65** [files-community/Files#5394]
**Explain the bug**
Renaming a file from test.txt to test doesn't work. it will just not rename and changing the actual file name with the extension also will just add it back.

**Expected behaviour**
The file extension should be removed

**Logfile**
[debug.log](https://github.com/files-community/Files/files/6793142/debug.log)
[debug_fulltrust.log](https://github.com/files-community/Files/files/6793143/debug_fulltrust.log)
 
**System Information**
 - OS Version: Windows 10 21H1 19043.1083
 - App version: v1.5.62

**Comment by winston-de** [comment]
@gave92 Could this bug have been introduced in #5342?

**Comment by gave92** [comment]
It looks like it's done on purpose (FileSystemHelpers.cs):

```cs
if (Path.HasExtension(source.Path) && !Path.HasExtension(newName))
{
    newName += Path.GetExtension(source.Path);
}
```

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5403.

**Comment by winston-de** [comment]
This bug still seems to repro on the latest version; no exceptions are logged.

**Comment by stanleyowen** [comment]
Fyi, I can't repro this issue on v1.9.11.0 :/

https://user-images.githubusercontent.com/69080584/126769101-fb45d952-e757-41f7-9462-949da60f7857.mp4

**Comment by josh-65** [comment]
It hasn't been an issue for me since v1.9
