### ISSUE TITLE
When starting files by pressing enter instead of clicking, resize bar/scrollbar on the left panel is focused

### ISSUE THREAD

**Issue by andreaslutsch** [files-community/Files#5685]
### Description

When starting Files, the resize edge/bar of the left panel is focused.

https://user-images.githubusercontent.com/7101531/128203984-cd964e41-dccd-4e69-a4ec-b28cac18bab5.mp4

### Steps To Reproduce

1. Start Files
2. See that resize edge/bar is focused.

### Expected behavior

This element should not be focused on startup of Files. 

### Files Version

v1.9.18.0

### Windows Version

Windows 10 Pro 21H1 19043.1151

**Comment by yaichenbaum** [comment]
@andreaslutsch where are you opening Files from (ie the start menu, taskbar, keyboard shortcut etc)?

**Comment by andreaslutsch** [comment]
I was opening Files here from the search menu of Windows. Searching for files and starting it with Enter.

It seems opening it from anywhere with the keyboard by pressing enter instead of clicking on the icon, the bar gets focused.
If I open by clicking, there is nothing focused.

**Comment by yaichenbaum** [comment]
This is the intentional design when opening the app via the keyboard, however we should look into focusing on a different control instead.

**Comment by Darhagonable** [comment]
Usually programs won't focus anything until user presses tab since it's common for users to start it with enter without wanting to use it with keyboard.

**Comment by yaichenbaum** [comment]
@Darhagonable you'll notice that many inbox apps have the same behavior in this regard.

**Comment by tellmewhy12** [comment]
> This is the intentional design when opening the app via the keyboard, however we should look into focusing on a different control instead.

@yair100 It gets focused for me just opening it from the Taskbar or Start (no keyboard input needed)

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5764.

**Comment by tellmewhy12** [comment]
> This issue should be resolved with #5764.

@yair100 still happening for me in 1.9.23.0
OS Version: 10.0.19043.1110

**Comment by esibruti** [comment]
@yaichenbaum we can close this issue

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5829.
