### ISSUE TITLE
Files crashes on Windows 10 1809

### ISSUE THREAD

**Issue by xezrunner** [files-community/Files#5905]
### Description

The app takes a long time to populate the side panel / drives.
Trying to open a folder crashes the app.

### Steps To Reproduce

1. Open Files.
2. Try navigating to a folder.
3. Observe the app crashing.

### Expected behavior

The app should be able to navigate into folders.

### Files Version

v1.9.26.0

### Windows Version

Windows 10 1809 17763

### Relevant Assets

[debug.log](https://github.com/files-community/Files/files/7032411/debug.log)

https://user-images.githubusercontent.com/8061077/130458757-d3b412ea-0ac7-4085-b822-104132968096.mp4

**Comment by gave92** [comment]
Is this a new behavior of 1.9.26? Was it working for you 1.9.25 or prior (if you had it)?

**Comment by yaichenbaum** [comment]
This issue should be resolved with #5914.

**Comment by xezrunner** [comment]
It's still crashing here, unfortunately.

[debug.log](https://github.com/files-community/Files/files/7041632/debug.log)
`debug_fulltrust.log` is empty.


https://user-images.githubusercontent.com/8061077/130677263-c081800f-bedd-45be-a4f4-52a86d5600be.mp4
