### ISSUE TITLE
Bug: Unable to drag and drop files from desktop to Files app

### ISSUE THREAD

**Issue by Zilla0617** [files-community/Files#6309]
### Description

Unable to move files from computer to Files app. For example, a word file on the desktop; when attempting to drag the file into Files app it will not work

### Expected behavior

I expect the file to move to the desired location

### Files Version

v2.0.13

### Windows Version

 Windows 10 Professional (x64) Build 19043.1266 (21H1)

**Comment by RodrigoBG13** [comment]
I have the same issue on Windows 11. Can't drag and drop any kind of file from outside the Files app into it.

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by yaichenbaum** [comment]
Can you share a screen recording so I can make sure I'm using the same steps on my end?

**Comment by yaichenbaum** [comment]
@Zilla0617 it looks like you're still using the stable version in the screen recording, can you try with preview build?

**Comment by Zilla0617** [comment]
https://user-images.githubusercontent.com/71089409/196583212-432d878e-ad7b-4777-9d88-9c89b8814e14.mp4

Same result with preview version

**Comment by yaichenbaum** [comment]
Thank you for the recordings, I can confirm that I've tried these steps and cannot reproduce the issue. I think we need to continue trying to reproduce this on our end before we can work on a fix.

**Comment by hecksmosis** [comment]
Windows 11 21H2 here (Files 2.4.8.0): It doesn't let me drag items to the main file list, only to the pinned files and folders on the sidebar.

**Comment by yaira2** [comment]
Can you try again in the latest preview? We made some changes that we think will help.

**Comment by Josh65-2201** [comment]
https://files.community/download

**Comment by Zilla0617** [comment]
It still doesn’t in the latest preview version, 2.4.54.0. Is there some setting I’m missing when it comes to turning on this feature, it never works for me.

**Comment by ZCRP** [comment]
i am here for the same problem i come form my own post [https://github.com/files-community/Files/issues/12136](url) #12136

**Comment by nitesh31mishra** [comment]
I can see this issue resolved in the latest version of Windows 11(V-22H2)

**Comment by Zilla0617** [comment]
Unfortunately, I’m not on Windows 11.  With latest version from the Microsoft Store on Windows 10 (.2965) I still encounter the same issue.

**Comment by Lukiluc29** [comment]
Moving from the desktop to the Files application currently works on my stable version (v2.5.1.0) but the reverse does not work for me (moving the Files application to the desktop).

**Comment by hishitetsu** [comment]
@Zilla0617 could you upload debug.log of the failed drag and drop?

**Comment by QuaintMako** [comment]
The drag and drop process works both ways on 2.5.21.0 Preview for me.

I'm on a W10-10.0.19045.3208 in non-admin process.

**Comment by Lukiluc29** [comment]
For me too, but the only issue is that when we move an item from Files to the desktop, it displays a context menu, and then we have to click on "Move here".

**Comment by hishitetsu** [comment]
I can't reproduce it either. However, it seems that some users actually fail to drag and drop.

**Comment by Lukiluc29** [comment]
> I can't reproduce it either. However, it seems that some users actually fail to drag and drop.

You should ask on Discord if some users are unable to drag and drop

**Comment by idelarca** [comment]
Has this issue been resolved?  I recently purchased the app in the Microsoft App Store in Windows 11.  For whatever reason, I can't drag and drop any kind of file from outside the Files app into it nor can I drag and drop a file between folders in the Files app.  Any suggestions?

**Comment by willibrandon** [comment]
When dragging a file from File Explorer to Files, Files sets the [AcceptedOperation](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.drageventargs.acceptedoperation) when the file is on the same drive to [DataPackageOperation.Move](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackageoperation). Mentioned previously, and I've confirmed, that move operation does not succeed.

However, when dragging a file from File Explorer file to Files, Files sets the `AcceptedOperation` to `DataPackageOperation.Copy` when the file is on a different drive. In my testing, that copy operation does succeed.

For some reason it seems that when dragging a file from File Explorer and the `AcceptedOperation` has been set to `DataPackageOperation.Move`, the drop event never fires.

**Comment by willibrandon** [comment]
I could submit a PR to help facilitate the discussion.

**Comment by yaira2** [comment]
Fyi @hishitetsu @gave92

**Comment by willibrandon** [comment]
After more testing, my original analysis was off.

I'm unable to drag and drop from Explorer only when dragging a file from the Windows recent files and/or favorites list. This is on a Windows 11 machine. When I drag and drop from a normal folder, the move operation works as expected.

I believe my issue is unrelated to this issue.

**Comment by willibrandon** [comment]
Closing #14454 since I no longer believe that would be an appropriate solution.

**Comment by willibrandon** [comment]
Honestly, I think the issue others have had here dragging and dropping from Explorer is when Files is running elevated. The same problem exists if you run Notepad elevated (Right click | Run as Administrator), and try and drag-and-drop a file from Windows Explorer.

https://web.archive.org/web/20190118125513/https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

**Comment by yaira2** [comment]
I've been able to repro them without running Files as admin.

**Comment by willibrandon** [comment]
> I've been able to repro them without running Files as admin.

Interesting. I'll keep looking and see if I can learn more. Drag and drop is an area that I like to help out with if possible.

**Comment by DerekZiemba** [comment]
All apps on my machine run as admin.   
I can't remember how or when I made the machine this way (well over a year ago) but it was to solve similar issues with moving/pasting/copying/dropping between for example: VSCode, Notepad++, Explorer, FastCopy, Ditto, etc. 
 
I'm unsure of a way to opt-out of admin for specific apps, but I believe doing so would stop Files from working with all the other apps that _are_ running as admin. For that reason, could drag/drop in File be made to work with   its fellow admin apps?

**Comment by Josh65-2201** [comment]
That is not related to this issue. But either way drag and drop won't work with Files as admin because of a Windows/WinAppSDK issue.

**Comment by DerekZiemba** [comment]
Bummer. I was able to force it to run without privileges with some help from  
https://superuser.com/questions/1749696/parameter-is-incorrect-when-using-runas-with-trustlevel-after-windows-11-22h2#comment2726286_1755207 

`runas /trustlevel:0x20000 /machine:amd64 "C:\Program Files\WindowsApps\Files_3.7.11.0_x64__1y0xx7n9077q4\Files.App\Files.exe"`

This gives the ability to drag/drop from Files to both Explorer & VSCode for some reason.  They must have some kind of workaround. Unfortunately though, no other app will accept a drop from `Files` & nothing can drop into `Files`

**Comment by Josh65-2201** [comment]
@Zilla0617 Is this still an issue on v4.0.11 https://files.community/download

**Comment by Josh65-2201** [comment]
@Zilla0617 Can you answer the above question

**Comment by Zilla0617** [comment]
I no longer use app and haven't in a long time.
