### ISSUE TITLE
Bug: Delete shortcuts don't work on search results

### ISSUE THREAD

**Issue by alirezanoori1986** [files-community/Files#7217]
### Description

There are a lot of issues with file operations when you search.

### Steps To Reproduce

1. Go to a folder and search for anything
2. Select an item
3. Hit "Delete" on the keyboard (or Shift + Delete)
4. Observe that the item isn't deleted

### Requirements
- Shortcuts should work as expected 

### Files Version

v2.3.49

### Windows Version

Windows 11 10.0.22000.348

### Relevant Assets/Logs

N/A

**Comment by yaichenbaum** [comment]
Is this still an issue in the preview build? https://files.community/download/preview

**Comment by sthivaios** [comment]
What do you mean? Delete and Shift+Delete work perfectly fine. @yair100 This was opened on December 5th 2021. It is outdated, and fixed by now. It think you should close it.

**Comment by yaichenbaum** [comment]
@sthivaios while it may work correctly on our devices, there are a lot of configurations out there and it's best to see if the issue was resolved for the person who reported it.

**Comment by alirezanoori1986** [comment]
I just tried this. The problem is still there for ALL of the mentioned points on build 2.3.12.0
Also downloaded the latest preview version (2.3.49.0), again. ALL of the issues exist.

@sthivaios maybe try to read the text one more time?

BTW, the preview was extremely buggy so if you're really thinking about releasing it, don't.

**Comment by yaichenbaum** [comment]
@alirezanoori1986 can you update the issue description with steps to reproduce this issue?

**Comment by alirezanoori1986** [comment]
@yair100 just did

**Comment by yaichenbaum** [comment]
> lots of files

Can you clarify how many?

**Comment by alirezanoori1986** [comment]
I've tested it on a folder with 68 files and 6 subdirectories.

The right click-delete worked in a folder that had "Thumbnails" view (only pictures) but didn't work on the folder with "Details" view.

**Comment by yaichenbaum** [comment]
That's useful to know 👍 
We're going to continue investigating this.

**Comment by yaichenbaum** [comment]
Merging with #10039
