### ISSUE TITLE
No under permission warning when renaming some specific files

### ISSUE THREAD

**Issue by tim103117** [files-community/Files#8326]
### Description

No under permission warnings are shown when renaming Utilman.exe to Utilman2.exe under system32

### Steps To Reproduce

1. Go to system32
2. find Utilman.exe
2. Rename it to Utilman2.exe
3. Select "Yes" for UAC
4. Nothing changed.

### Expected behavior

There is no rename failure message. Normally it should tell us to get permission from TrustedInstaller

### Files Version

Version: 2.1.13.0

### Windows Version

Windows 11 Dev 22543.1000

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8054901/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8054902/debug.log)

2022-02-13

**Comment by KumarjitDey** [comment]
+1 this

**Comment by Lukiluc29** [comment]
This should be merged with #13229 as it's an issue related to administrator permissions.

**Comment by Josh65-2201** [comment]
There wasn't support for renaming in the initial PR. So I don't think it should be merged.

**Comment by yaira2** [comment]
I can confirm these are separate issues.

**Comment by yaira2** [comment]
@gave92 is this addressed or was that only for copy and delete?

**Comment by yaira2** [comment]
@tim103117 I think this is resolved in the latest preview build https://files.community/download.

**Comment by gave92** [comment]
Not solved, this issue is different. This is about showing an error for files you can't rename even as administrator (this dialog from FE)
<img width="547" alt="image" src="https://github.com/files-community/Files/assets/9673091/aeeafb1d-0958-4ec4-865c-e9c43c812dae">

**Comment by ferrariofilippo** [comment]
How detailed should the dialog be?
![image](https://github.com/files-community/Files/assets/102259289/60178cf9-1e86-4a82-bd38-c918ef5005e5)
Is something like this okay? Should we add any other info?

**Comment by yaira2** [comment]
Title: "Failed to rename item"
Content: "Editing `path` requires permission from TrustedInstaller."
Primary action: "OK"
Secondary action: "Edit permissions"

**Comment by ferrariofilippo** [comment]
> Secondary action: "Edit permissions"

Should this action open the `Advanced Security` tab in the `Properties` window?

**Comment by yaira2** [comment]
Opening the regular security page is probably easier.
