### ISSUE TITLE
Cannot replace "Files explorer" to "Files" (Alternative solution in the comment)

### ISSUE THREAD

**Issue by Xiarno** [files-community/Files#8707]
### Description

I sideloaded the app as indicated in the instruction and then activated the thing to switch to "files". However, when I open a folder on my desktop, it still opens as in "File explorer". Also when I press Windows + E, it still opens "File Explorer"

### Steps To Reproduce

1. Launch the sideload version of the app.
2. Press the "settings" icon on the top right and navigate to the "experimental" tab.
3. Toggle "On" the "Default File Manager" option.
4. Try to open any folder on the desktop and press "Windows + E"

### Expected behavior

The "Files" app open.

### Files Version

Version: 2.1.15.0 OS Version: 10.0.19042.1586

### Windows Version

20H2

### Relevant Assets/Logs

[debug.log](https://github.com/files-community/Files/files/8308505/debug.log)

**Comment by Xiarno** [comment]
After searching for a bit, I managed to find a way to do it, since the automatic way does not work. This is following the instruction on this exact page: https://files-community.github.io/docs/#/articles/replace-file-explorer
Note that the website automatically redirects you to the new version of the website. However, I managed to screenshot the page before the redirect happens and I followed the instructions.

How to do it:

1. Open the registry editor
2. Create a backup of the registry. Make sure to store the backup in your desktop folder so that you can access it in the event that Files won't open.
3. Navigate to `HKEY_CURRENT_USER\SOFTWARE\Classes\Directory`.
4. Create a key named `shell` and set the default key value to `openinfiles`.
5. Create a key named `openinfiles` under `shell`.
6. Create a key named `command` under `openinfiles` and set the default key value to: `C:\Users\<YOURUSERNAME>\Appdata\Local\Microsoft\WindowsApp\files.exe -Directory %1`.

I hope this help. I will still keep the bug open as the automatic function in the app doesn't work but this is an alternative.

**Comment by Josh-65** [comment]
The app function does work and should do what you have just listed. It likely windows blocking it in some way. Especially if the unsetasdefault.reg script doesnt work either.

**Comment by Xiarno** [comment]
> The app function does work and should do what you have just listed. It likely windows blocking it in some way. Especially if the unsetasdefault.reg script doesnt work either.

@Josh-65 Is there any way to check if Windows blocked it ?

**Comment by Josh-65** [comment]
I dont think there an "windows has blocked this" message other than what the logs say in files. but it seem a small amount of people carnt use it for no apparent reason as far as i know. in those cases the reg script work for them.

**Comment by Xiarno** [comment]
Then I'll gives this link: https://raw.githubusercontent.com/files-community/files-community.github.io/main/data/SetFilesAsDefault.zip

This link is a file that was in the website I mentioned in my first comment. I cannot garantee it'll work since I went the manual way.

I cannot really help more than that. It didn't work for me using the button directly in the app so I searched for an alternative way and found this way that worked so for the technicalities, I'm gonna let you people work on this. If you need any files / logs that could help, I'll do my best.

**Comment by Josh-65** [comment]
Did you try the scripts before manualy doing it?

**Comment by Xiarno** [comment]
I said it, I went the manual way. But the manual way described worked so I guess this automatic way based on the manual would too, but I cannot say yes or no and I'll not search further than this since my own problem has been resolved.

**Comment by Josh-65** [comment]
In that case i will close this and anyone linked to this can still see solutions.
