### ISSUE TITLE
Set Files as the default file manager doesn't work

### ISSUE THREAD

**Issue by martymarty004** [files-community/Files#8749]
### Description

After updating to v2.1.24 (Preload) and later (I tried 2.1.25, 2.1.26 and 2.1.27 preview version), it is not possible to set Files as the default file manager any more.

Turning on the option will make the changes to the registry, but when I try opening a folder, the following error appears:

> This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page.

![image](https://user-images.githubusercontent.com/61474670/159699961-27f0f9b1-84ad-4127-957e-e22c967656e8.png)

This happens for every action that regards opening File Explorer, maybe the registry keys are pointing to the wrong location(?)

### Steps To Reproduce

1. Open Files
2. Go to the settings page and enable "Set Files as the default file manager"
3. Try something that requires the opening of File Explorer
4. The error will be shows

### Expected behavior

Files should set correctly as the default file explorer.

### Files Version

Versione 2.1.27.0 OS Version: 10.0.22000.556

### Windows Version

Windows 11 21H2 22000.556

### Relevant Assets/Logs

[debug_fulltrust.log](https://github.com/files-community/Files/files/8333004/debug_fulltrust.log)
[debug.log](https://github.com/files-community/Files/files/8333005/debug.log)

**Comment by martymarty004** [comment]
Maybe it's the same issue as #8707, but I decided to report it just to be sure.

**Comment by martymarty004** [comment]
@yair100 nope, the issue still persists. The option applies the changes to the registry and reverts them back correctly.

By looking at the changes, I can see that the file that some registry keys mention doesn't actually exist.

For example, this one: `[HKEY_CLASSES_ROOT\Folder\shell\explore\command] ->"%LOCALAPPDATA%\Files\FilesLauncher.exe" "%1"`
![image](https://user-images.githubusercontent.com/61474670/159710643-726f4cae-c47b-45be-b197-43dd74ad19ab.png)

**Comment by yaichenbaum** [comment]
@gave92 can you help with this?

**Comment by gave92** [comment]
Hi, it would be a huge help if you could check the following (using Files 2.1.27):

1) Run the [reg file](https://raw.githubusercontent.com/files-community/Files/main/src/Files.Launcher/Assets/FilesOpenDialog/UnsetFilesAsDefault.reg) linked by Yair above to revert registry changes and "start clean" -> File Explorer should open as default
2) Open a file explorer window and leave it open, just in case. You'll be able to navigate with it by using the address bar or by right-clicking a folder and choosing "open in new window"
3) Toggle the setting to enable Files as default from Settings > Experimental -> Do you get the request for admin access? Does the toggle stay "on" after granting it?
4) Verify that the following registry key was applied: `[HKEY_CLASSES_ROOT\Folder\shell\explore\command] ->"%LOCALAPPDATA%\Files\FilesLauncher.exe" "%1"`
5) Verify that the following file exist: `%AppData%\Local\Packages\Files_1y0xx7n9077q4\LocalState\FilesOpenDialog`
6) Verify that the following file exist: `%AppData%\Local\Files\FilesLauncher.exe"`

Feel free to reach us on our [Discord channel](https://discord.com/invite/files) if you have questions or if you get stuck. Thanks!

**Comment by martymarty004** [comment]
@gave92 OK, I did everything that you asked.

I run the file to revert registry changes and reinstalled the latest preview version of Files.

When I click the option, it does trigger UAC, and it stays on after I approve the request.
The registry key is added correctly.

`%AppData%\Local\Packages\Files_1y0xx7n9077q4\LocalState\FilesOpenDialog\FilesLauncher.exe` exists.
The folder `%AppData%\Local\Files\` does **not** exist.

**Comment by martymarty004** [comment]
`%AppData%\Local\Files\` is also missing on my laptop, where I have installed Files for the first time. (Release 2.1.24, sideloaded)

**Comment by gave92** [comment]
Waait could be because you username has spaces in it?

**Comment by martymarty004** [comment]
The username is indeed identical on both machines, with a space in between.

**Comment by gave92** [comment]
Could you also check what happens if you give the following commands to Powershell? Does the missing file/folder get created? What does it print to console?
```cs
$destFolder = [System.Environment]::ExpandEnvironmentVariables("%LocalAppData%\Packages\Files_1y0xx7n9077q4\LocalState\FilesOpenDialog")
Write-Host $destFolder
$dataPath = [System.Environment]::ExpandEnvironmentVariables("%LocalAppData%\Files")
Write-Host $dataPath
New-Item -Force -Path $dataPath -ItemType Directory
Copy-Item -Filter *.* -Path "$destFolder\*" -Recurse -Force -Destination "$dataPath"
```

**Comment by gave92** [comment]
Note: when you get tired and just want to make it work you can just manually copy the file "FilesLauncher.exe" to `%AppData%\Local\Files` ;)

**Comment by martymarty004** [comment]
![image](https://user-images.githubusercontent.com/61474670/159805797-11482514-6327-44d1-b4fc-a816307de74f.png)

**Comment by gave92** [comment]
Ouch ok should be working now but I fail to understand what the problem is -.- The above is the command we execute i Files to copy the files over.

**Comment by martymarty004** [comment]
Now that the files actually exist, it does work properly.

**Comment by martymarty004** [comment]
So, manually it works but when it should do that automatically it doesn't, do I understand that right?

**Comment by martymarty004** [comment]
OK, thanks to your help, I managed to get Files working properly on both of my machines. 
The only thing left to do now is finding the cause of this odd behaviour.

Do I have to leave this issue open, so you can keep track of it, or I should close it? 


Just one more thing: 
I commented on an issue (bug) that was closed because there was information missing. 
Could you please tell me if it has been noticed and if it's been taken care of? #8569

**Comment by Josh-65** [comment]
Odd i get this too. I tryed doing what was said above and just get the windows error sound with no message. I did try runing the .exe myself (I presume this is suppost to open files) but i get this 
![image](https://user-images.githubusercontent.com/26977075/160260133-5abf1378-457a-4d83-a282-aafd4235dcb2.png)

**Comment by gave92** [comment]
Confirmed that this is due to usernames with a space

**Comment by yaichenbaum** [comment]
This issue should be resolved in `main`.

**Comment by Josh-65** [comment]
It seem this has not fully been fixed as - and potentially other special charater still have the issue. As soski has said in the discord server (https://discord.com/channels/725513575971684472/725514946112127057/959156418336927814)
